macro(add_compiler_flags)
    parse_arguments(ARG "" "C;CXX;DEBUG;RELEASE" ${ARGN})
    
    if(NOT ARG_DEBUG AND NOT ARG_RELEASE)
      foreach(flag ${ARG_DEFAULT_ARGS})
        set(flags_list "${flags_list} ${flag}")
      endforeach()
      set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${flags_list}")
      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${flags_list}")
    endif()

    if(ARG_DEBUG)
      foreach(flag ${ARG_DEFAULT_ARGS})
        set(flags_list "${flags_list} ${flag}")
      endforeach()
      set(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} ${flags_list}")
      set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} ${flags_list}")
    endif()

    if(ARG_RELEASE)
      foreach(flag ${ARG_DEFAULT_ARGS})
        set(flags_list "${flags_list} ${flag}")
      endforeach()
      set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} ${flags_list}")
      set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} ${flags_list}")
    endif()
endmacro()
