# set this with cmake -DCMAKE_INSTALL_PREFIX=/where/to/install
set(INSTALL_DIR ${CMAKE_INSTALL_PREFIX})
set(BIN_INSTALL_DIR ${INSTALL_DIR})
set(LIB_INSTALL_DIR ${INSTALL_DIR}/lib)
set(DATA_INSTALL_DIR ${INSTALL_DIR})
